// Generic content-block widgets — not tied to any Hubzilla app or route.
// All are multiInstance + configurable and live only in user layouts
// (defaultModules: []), placeable on any module's pages.

import { registerModule } from "@/shared/lib/module-registry";
import { useI18n } from "@/i18n";

registerModule({
  id: "blocks",
  routes: [],
  widgets: [
    {
      // Site copyright + "Powered by Hubzilla" + active theme — global, so it
      // always renders in the footer slot on every page, on by default.
      id: "blocks.credits",
      label: () => useI18n().t("widgets.credits"),
      loader: () => import("./widgets/CreditsWidget"),
      slot: "footer",
      contexts: "any",
      global: true,
    },
    {
      id: "blocks.rss",
      label: () => useI18n().t("widgets.rss_feed"),
      loader: () => import("./widgets/RssWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/RssConfig"),
      helpTarget: "widgets.rss_feed_widget",
    },
    {
      id: "blocks.html",
      label: () => useI18n().t("widgets.html_block"),
      loader: () => import("./widgets/HtmlBlockWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/HtmlBlockConfig"),
      helpTarget: "widgets.html_block_widget",
    },
    {
      id: "blocks.clock",
      label: () => useI18n().t("widgets.clock_card"),
      loader: () => import("./widgets/ClockWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/ClockConfig"),
      helpTarget: "widgets.clock_card_widget",
    },
    {
      // Owner productivity tool, not page content — hidden from visitors
      id: "blocks.pomodoro",
      label: () => useI18n().t("widgets.pomodoro"),
      loader: () => import("./widgets/PomodoroWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      visitorVisible: false,
      configComponent: () => import("./widgets/PomodoroConfig"),
      helpTarget: "widgets.pomodoro_widget",
    },
    {
      id: "blocks.weather",
      label: () => useI18n().t("widgets.weather"),
      loader: () => import("./widgets/WeatherWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/WeatherConfig"),
    },
    {
      id: "blocks.quote",
      label: () => useI18n().t("widgets.quote_of_day"),
      loader: () => import("./widgets/QuoteWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
    },
    {
      id: "blocks.embed",
      label: () => useI18n().t("widgets.embed"),
      loader: () => import("./widgets/EmbedWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/EmbedConfig"),
    },
    // Same components as above, registered again under slot "mainTop" so
    // they can also be dropped into HQ's top banner slot — widget slot is
    // fixed per definition, so a second id is needed for the second slot.
    {
      id: "blocks.clock_top",
      label: () => useI18n().t("widgets.clock_card"),
      loader: () => import("./widgets/ClockWidget"),
      slot: "mainTop",
      defaultModules: [],
      contexts: ["hq"],
      multiInstance: true,
      configComponent: () => import("./widgets/ClockConfig"),
      helpTarget: "widgets.clock_card_widget",
    },
    {
      id: "blocks.weather_top",
      label: () => useI18n().t("widgets.weather"),
      loader: () => import("./widgets/WeatherWidget"),
      slot: "mainTop",
      defaultModules: [],
      contexts: ["hq"],
      multiInstance: true,
      configComponent: () => import("./widgets/WeatherConfig"),
    },
    {
      id: "blocks.quote_top",
      label: () => useI18n().t("widgets.quote_of_day"),
      loader: () => import("./widgets/QuoteWidget"),
      slot: "mainTop",
      defaultModules: [],
      contexts: ["hq"],
      multiInstance: true,
    },
    {
      id: "blocks.embed_top",
      label: () => useI18n().t("widgets.embed"),
      loader: () => import("./widgets/EmbedWidget"),
      slot: "mainTop",
      defaultModules: [],
      contexts: ["hq"],
      multiInstance: true,
      configComponent: () => import("./widgets/EmbedConfig"),
    },
    {
      // Horizontal nav bar fed by a Hubzilla menu — header only (always
      // full-width, unlike mainTop's masonry-packed banner widgets)
      id: "blocks.menu_bar",
      label: () => useI18n().t("widgets.menu_bar"),
      loader: () => import("./widgets/MenuBarWidget"),
      slot: "header",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/MenuConfig"),
      helpTarget: "widgets.menu_widgets",
    },
    {
      // Vertical multilevel menu fed by a Hubzilla menu — right sidebar only
      id: "blocks.menu_tree",
      label: () => useI18n().t("widgets.menu_tree"),
      loader: () => import("./widgets/MenuTreeWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/MenuConfig"),
      helpTarget: "widgets.menu_widgets",
    },
    {
      id: "blocks.links",
      label: () => useI18n().t("widgets.link_list"),
      loader: () => import("./widgets/LinkListWidget"),
      slot: "right",
      defaultModules: [],
      contexts: "any",
      multiInstance: true,
      configComponent: () => import("./widgets/LinkListConfig"),
      helpTarget: "widgets.link_list_widget",
    },
  ],
  permissions: [],
});
